#!/usr/bin/env python

import click

from clacks.configuration import _load_config

@click.group()
def cli():
    pass

@click.command()
@click.argument('key')
def get(key):
    config = _load_config()
    print config[str(key)]

@click.command()
@click.argument('key')
@click.argument('value')
def set(key, value):
    config = _load_config(False)
    print "Setting '%s' to %r" % (str(key), value)
    config[str(key)] = value
    config.close()
    print "Done"

@click.command()
def get_all():
    config = _load_config()
    for k,v in config.iteritems():
        print "'%s' = %r" % (k,v)

if __name__ == '__main__':
    cli.add_command(get)
    cli.add_command(get_all)
    cli.add_command(set)

    cli()
